select * from customer limit 20

--1.What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--2.Which customers used a discount but still spent more than the avg purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3.Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as AveragePR
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--4.Compare the average Purchase amounts between Standard and Express Shipping.
select shipping_type, ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--5. Do subscribed customers spend more? Compare avg spend and total revenue between subscribers and non-subscribers.
select subscription_status, COUNT(customer_id) as total_custoners, ROUND(AVG(purchase_amount),2) as avg_spend, ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_spend, total_revenue desc;

--6.Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, Round(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7.Segment customers into New, Returning, and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment, count(*) as Number_of_customers
from customer_type
group by customer_segment

(or)

SELECT customer_segment,
COUNT(*) AS Number_of_customers
FROM (
    SELECT customer_id,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS customer_type
GROUP BY customer_segment;

select customer_segment, count(*) as Number_of_customers
from customer_type
group by customer_segment

--8.What are the top 3 most purchased products within each category?
SELECT 
    c1.category,
    c1.item_purchased,
    COUNT(c1.customer_id) AS total_orders
FROM customer c1
GROUP BY c1.category, c1.item_purchased
HAVING (
    SELECT COUNT(*)
    FROM (
        SELECT c2.item_purchased
        FROM customer c2
        WHERE c2.category = c1.category
        GROUP BY c2.item_purchased
        HAVING COUNT(c2.customer_id) > COUNT(c1.customer_id)
    ) AS higher_items
) < 3
ORDER BY c1.category, total_orders DESC;

--9.Are customers who are repeat buyers (more then 5 previous purchases) also likely to subscribe?
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10.What is the revenue contribution of each age group?
select age_group, SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;